encoding: utf-8

# SEO相关信息
title: Echo WORK
description: 日本車、地図制作チーム
keywords: Echo,WORK,Maps,Cars,Mods
author: kKsk
footerText: 'By Echo WORK Members'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://echo-work.ltd/'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/413721

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 主页
    url: /
  - title: 车辆品牌
    url: /pages/Brands.html
  - title: 地图
    url: /pages/Maps.html
  - title: 搜索
    url: /pages/search.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: 我们的Bilibili
    url: https://space.bilibili.com/493274956
  - title: QQ群加群链接
    url: https://jq.qq.com/?_wv=1027&k=g2pfZTDa
